#!/bin/bash
#
# testing.sh - perform testing for sudoku
#
# usage: run 'make test' and redirect to a directory as needed 
#
# ./sudoku command

# make Sudoku
make

# incorrect command line arguments
./sudoku solve and create

################ creator ################
# generate a random sudoku 5 time and solve them
dir=tests
for i in {1..3}; do
    # create a new random sudoku and save it
    ./sudoku create > "$dir/create$i"

    # wait 1 second between each iteration to generate a different sudoku as srand depends on time
    sleep 1 
done

################ solver ################
# invalid sudoku 
./sudoku solve < tests/test0 

# sudoku with multiple solutions
./sudoku solve < tests/test1 

# valid sudoku with unique solution
./sudoku solve < tests/test2 

# valid sudoku with unique solution generated by the creator
# solve the three random sudoku generated earlier
for i in {1..3}; do
    ./sudoku solve < "$dir/create$i"
done

# fuzz testing with fuzzSudoku
printf "fuzz testing\n"
for i in {1..3}; do
    ./fuzzSudoku "$i"
done